### ISSUE TITLE
'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by augenstern-lwx** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#111]
Hi, I was trying to train the model, but it says like this in the third step:

Traceback (most recent call last):
  File "train.py", line 170, in <module>
    args.checkpoint_after, args.val_after)
  File "train.py", line 80, in train
    for batch_data in train_loader:
  File "/root/miniconda3/envs/myconda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/root/miniconda3/envs/myconda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "/root/miniconda3/envs/myconda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/root/miniconda3/envs/myconda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/lightweight-human-pose-estimation.pytorch-master/datasets/coco.py", line 46, in __getitem__
    sample = self._transform(sample)
  File "/root/miniconda3/envs/myconda/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 49, in __call__
    img = t(img)
  File "/home/lightweight-human-pose-estimation.pytorch-master/datasets/transformations.py", line 10, in __call__
    h, w, _ = sample['image'].shape
AttributeError: 'NoneType' object has no attribute 'shape'

What's happening? Can somebody help me? thank u

**Comment by Daniil-Osokin** [comment]
Hi! `sample['image']` is `None`, but should be a `numpy` array. Did you pass a proper path to train images folder wth `--train-images-folder`?

**Comment by augenstern-lwx** [comment]
Hi!Thank you for your reply! I think my path is true？My path is:"python train.py --train-images-folder coco2017/train2017/ --prepared-train-labels prepared_train_annotation.pkl --val-labels val_subset.json --val-images-folder coco2017/val2017/ --checkpoint-path coco2017/mobilenet_sgd_68.848.pth.tar --from-mobilenet". Could it be a problem with my dataset label？My COCO dataset label names are "numble"+".jpg", such as"000000000395.jpg".

**Comment by Daniil-Osokin** [comment]
To check this, add `print(os.path.join(self._images_folder, label['img_paths'])` after the [line 37](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/datasets/coco.py#L37) and pass `--num-workers 0` to the `train.py`. It will print image path which it tries to load. Then just check if image exists by this path.

**Comment by augenstern-lwx** [comment]
Thank you for your advice！ I will check it again.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
