### ISSUE TITLE
Error when converting to onnx

### ISSUE THREAD

**Issue by SingL3** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#12]
Hello, this work is excellent! And now I am trying to run the demo, I first just want to test the inference time. So I downloaded the checkpoint_iter_370000.pth and trying to convert it into onnx. And I got this error:
> Traceback (most recent call last):
  File "convert_to_onnx.py", line 30, in <module>
    convert_to_onnx(net, args.output_name)
  File "convert_to_onnx.py", line 16, in convert_to_onnx
    torch.onnx.export(net, input, output_name, verbose=True, input_names=input_names, output_names=output_names)
  File "/home/lin/anaconda3/envs/panet/lib/python3.6/site-packages/torch/onnx/__init__.py", line 25, in export
    return utils.export(*args, **kwargs)
  File "/home/lin/anaconda3/envs/panet/lib/python3.6/site-packages/torch/onnx/utils.py", line 84, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names)
  File "/home/lin/anaconda3/envs/panet/lib/python3.6/site-packages/torch/onnx/utils.py", line 140, in _export
    trace.set_graph(_optimize_graph(trace.graph(), aten))
  File "/home/lin/anaconda3/envs/panet/lib/python3.6/site-packages/torch/onnx/utils.py", line 95, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, aten)
  File "/home/lin/anaconda3/envs/panet/lib/python3.6/site-packages/torch/onnx/__init__.py", line 40, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/lin/anaconda3/envs/panet/lib/python3.6/site-packages/torch/onnx/utils.py", line 368, in _run_symbolic_function
    return fn(g, *inputs, **attrs)
TypeError: elu() got an unexpected keyword argument 'scale' (occurred when translating elu)

Any idea how to solve this?
By the way, I am using pytorch 0.4.0 and python 3.6.6.
Thank you!

**Comment by Daniil-Osokin** [comment]
Hi! I've tested with `onnx 1.4.1`, may be `onnx` needs update?

BTW, to run python demo there is no need to convert to `onnx`, just use the provided checkpoint, and for c++ demo OpenVINO Toolkit has already converted models in the package.

**Comment by SingL3** [comment]
OK, I will update and try it. If it works, I will close this issue.
I see. What I want to do is to go through the flow.After that, I will re-train the model and convert it to openvino.

**Comment by SingL3** [comment]
@Daniil-Osokin 
Sorry to bother you again. The script you provide is using torch.onnx but not the the onnx from the environment, which I cannot manage its version. Did you mean to use the onnx from the environment but not torch.onnx?

**Comment by SingL3** [comment]
Now I use pytorch 1.0 and it works, thanks!
