### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by Yasminbr** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#228]
Hey , I am following your guide - in stage number 3 I run 
To train from MobileNet weights, run python train.py --train-images-folder <COCO_HOME>/train2017/ --prepared-train-labels prepared_train_annotation.pkl --val-labels val_subset.json --val-images-folder <COCO_HOME>/val2017/ --checkpoint-path <path_to>/mobilenet_sgd_68.848.pth.tar --from-mobilenet

But I got the following error - 
 
`C:\ProgramData\Anaconda3\envs\Myeloma1\lib\site-packages\torch\optim\lr_scheduler.py:134: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
Traceback (most recent call last):
  File "C:/Users/yasminbr/Desktop/School/Deep_Leraning/project/lightweight-human-pose-estimation.pytorch-master/train.py", line 170, in <module>
    args.checkpoint_after, args.val_after)
  File "C:/Users/yasminbr/Desktop/School/Deep_Leraning/project/lightweight-human-pose-estimation.pytorch-master/train.py", line 80, in train
    for batch_data in train_loader:
  File "C:\ProgramData\Anaconda3\envs\Myeloma1\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "C:\ProgramData\Anaconda3\envs\Myeloma1\lib\site-packages\torch\utils\data\dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "C:\ProgramData\Anaconda3\envs\Myeloma1\lib\site-packages\torch\utils\data\dataloader.py", line 1229, in _process_data
    data.reraise()
  File "C:\ProgramData\Anaconda3\envs\Myeloma1\lib\site-packages\torch\_utils.py", line 434, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\Myeloma1\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\ProgramData\Anaconda3\envs\Myeloma1\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\ProgramData\Anaconda3\envs\Myeloma1\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\yasminbr\Desktop\School\Deep_Leraning\project\lightweight-human-pose-estimation.pytorch-master\datasets\coco.py", line 46, in __getitem__
    sample = self._transform(sample)
  File "C:\ProgramData\Anaconda3\envs\Myeloma1\lib\site-packages\torchvision\transforms\transforms.py", line 61, in __call__
    img = t(img)
  File "C:\Users\yasminbr\Desktop\School\Deep_Leraning\project\lightweight-human-pose-estimation.pytorch-master\datasets\transformations.py", line 10, in __call__
    h, w, _ = sample['image'].shape
AttributeError: 'NoneType' object has no attribute 'shape'

Hope to get some help here, 
thanks 
`

**Comment by Daniil-Osokin** [comment]
Hi! I believe the path to the `<COCO_HOME>` directory with the extracted COCO dataset was not set properly. `<COCO_HOME>` should be the valid path to the directory with the COCO dataset.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
