### ISSUE TITLE
'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by sunbin1357** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#73]
Hi, I was trying to train the model, but it says like this:

AttributeError: Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/lightweight-human-pose-estimation.pytorch/datasets/coco.py", line 46, in __getitem__
    sample = self._transform(sample)
  File "/opt/conda/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 49, in __call__
    img = t(img)
  File "/home/lightweight-human-pose-estimation.pytorch/datasets/transformations.py", line 10, in __call__
    h, w, _ = sample['image'].shape
AttributeError: 'NoneType' object has no attribute 'shape'

What's happening? Can somebody help me? thank u

**Comment by augenstern-lwx** [comment]
Hi, I ran into the same problem. Can you tell me how you solved it?
